/* eslint-disable @typescript-eslint/naming-convention */

export enum Modal {
  OPEN_MODAL_SEARCH_TRD = 'OPEN_MODAL_SEARCH_TRD',
  CLOSE_MODAL_SEARCH_TRD = 'CLOSE_MODAL_SEARCH_TRD',
  //*
  OPEN_MODAL_CCD_USADOS = 'OPEN_MODAL_CCD_USADOS',
  CLOSE_MODAL_CCD_USADOS = 'CLOSE_MODAL_CCD_USADOS',
  //*
  OPEN_MODAL_CREACION_FORMATO_TIPO = 'OPEN_MODAL_CREACION_FORMATO_TIPO',
  CLOSE_MODAL_CREACION_FORMATO_TIPO = 'CLOSE_MODAL_CREACION_FORMATO_TIPO',
  //*
  OPEN_MODAL_BUSQUEDA_TIPOLOGIAS_DOCUMENTALES = 'OPEN_MODAL_BUSQUEDA_TIPOLOGIAS_DOCUMENTALES',
  CLOSE_MODAL_BUSQUEDA_TIPOLOGIAS_DOCUMENTALES = 'CLOSE_MODAL_BUSQUEDA_TIPOLOGIAS_DOCUMENTALES',
  //*
  OPEN_MODAL_ADMINISTRACION_TIPOLOGIAS_DOCUMENTALES = 'OPEN_MODAL_ADMINISTRACION_TIPOLOGIAS_DOCUMENTALES',
  CLOSE_MODAL_ADMINISTRACION_TIPOLOGIAS_DOCUMENTALES = 'CLOSE_MODAL_ADMINISTRACION_TIPOLOGIAS_DOCUMENTALES',
  //* modal administracion de TRD
  OPEN_MODAL_ADMINISTRACION_TRD = 'OPEN_MODAL_ADMINISTRACION_TRD',
  CLOSE_MODAL_ADMINISTRACION_TRD = 'CLOSE_MODAL_ADMINISTRACION_TRD',
  //* modal establecer tipologia documental a TRD
  OPEN_MODAL_ESTABLECER_TIPOLOGIA_DOCUMENTAL_A_TRD = 'OPEN_MODAL_ESTABLECER_TIPOLOGIA_DOCUMENTAL_A_TRD',
  CLOSE_MODAL_ESTABLECER_TIPOLOGIA_DOCUMENTAL_A_TRD = 'CLOSE_MODAL_ESTABLECER_TIPOLOGIA_DOCUMENTAL_A_TRD',
  //* historial de cambios
  OPEN_MODAL_HISTORIAL_CAMBIOS = 'OPEN_MODAL_HISTORIAL_CAMBIOS',
  CLOSE_MODAL_HISTORIAL_CAMBIOS = 'CLOSE_MODAL_HISTORIAL_CAMBIOS',
  // ? buttons, loading, etc
  CREATE_TRD_LOADING_BUTTON = 'CREATE_TRD_LOADING_BUTTON'
}

export const initialState = {
  modalSearchTRD: false,
  modalCCDUsados: false,
  modalCreacionFormatoTipo: false,
  modalBusquedaTipologiasDocumentales: false,
  modalAdministracionTipologiasDocumentales: false,
  modalAdministracionTRD: false,
  modalEstablecerTipologiaDocumentalATRD: false,
  modalHistorialCambios: false,
  // ? buttons, loading, etc
  createTRDLoadingButton: false
};
